/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web 控制台（静态单页） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/html */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                /** @description 静态文件缺失 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web 控制台（“/”的别名，静态单页） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/html */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活检查 + 存储后端 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 图谱统计 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphStats"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部人设及关联账号 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonaList"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部话题 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TopicList"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部规则（含确证状态/灰度字段） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuleList"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 决策流（近期行为 + DECIDED_VIA 引用，可解释性视图） */
        get: {
            parameters: {
                query?: {
                    /** @description 缺省 = 全账号合并，按 ts 倒序 */
                    account?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DecisionList"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 矩阵账号及状态（账号墙） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountList"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** 创建账号（含人设） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateAccountResult"];
                    };
                };
                /** @description 缺必填字段 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description OK */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量导入账号（单项失败不中断） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        accounts?: components["schemas"]["CreateAccountInput"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
                /** @description 列表项结构异常（当前实现） */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单账号全景（人设/状态/承诺/召回/情景/摘要） */
        get: {
            parameters: {
                query: {
                    /** @example acc:xiaohongshu:lily_beauty */
                    account: string;
                    /** @description 召回查询词（可选） */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountOverview"];
                    };
                };
                /** @description 缺 account 参数或账号不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 人可读记忆摘要（Markdown） */
        get: {
            parameters: {
                query: {
                    /** @example acc:xiaohongshu:lily_beauty */
                    account: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryDigest"];
                    };
                };
                /** @description 缺 account 参数或账号不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 服务端异常 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 知识检索（bigram 倒排，中文召回） */
        get: {
            parameters: {
                query?: {
                    /** @description 查询词（空 = 空结果） */
                    q?: string;
                    k?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResult"];
                    };
                };
                /** @description 畸形查询参数（如 k 非整数）当前返 500 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 两段式决策（阶段一规则闸门纯代码；阶段二 stub/LLM） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecideInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Decision"];
                    };
                };
                /** @description 缺必填字段；未知账号当前实现同样返 400（见 error 文本） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description OK */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 决策 → 执行规格（+执行器 argv）；闸门拦截时 spec=null */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanResult"];
                    };
                };
                /** @description 缺必填字段 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description OK */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 执行结果回写（幂等；发帖自动承诺扫描）
         * @description body 为 {"result": {...}}，或直接平铺 result 字段。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportResult"];
                    };
                };
                /** @description 缺必填字段 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description OK */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/{level}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 维护任务（幂等：漏跑补跑即可）
         * @description body 可选、当前被忽略（LLM 钩子走 CLI --llm）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    level: "daily" | "weekly" | "monthly" | "yearly";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MaintenanceSummary"];
                    };
                };
                /** @description 未知 level */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Health: {
            ok: boolean;
            /** @description 存储后端类名（KnowledgeStore / SQLiteKnowledgeStore / ...） */
            backend: string;
        };
        GraphStats: {
            nodes: number;
            edges: number;
            /** @description 仅 sqlite/neo4j 后端返回（事件日志数）；内存后端无此键 */
            events?: number;
        };
        /** @description 人设卡 + 人设属性（additionalProperties 承载领域扩展） */
        PersonaCard: {
            account_id: string;
            persona_id: string;
            interests: string[];
            name?: string;
            age_band?: string;
            occupation?: string;
            location?: string;
            mbti?: string;
            language_style?: string;
            bio?: string;
        };
        AccountState: {
            account_id: string;
            status: string | null;
            risk_level: string | null;
            age_days: number;
            cooldown_remaining_h: number;
            today_action_counts: {
                [key: string]: number;
            };
            last_summary: string | null;
            recent_actions: {
                action: string;
                topic_id?: string | null;
                digest?: string;
            }[];
        };
        AccountListItem: {
            account_id: string;
            status: string | null;
            risk_level: string | null;
            age_days: number;
            cooldown_remaining_h: number;
            today_action_counts: {
                [key: string]: number;
            };
            last_summary: string | null;
            recent_actions: {
                action: string;
                topic_id?: string | null;
                digest?: string;
            }[];
            name: string;
        };
        OpenPromise: {
            note_id: string;
            fact: string;
            ts?: number;
        };
        RecalledMemory: {
            note_id: string;
            fact: string;
            category?: string | null;
            pinned?: boolean;
            score: number;
        };
        Episode: {
            id: string;
            level: string;
            period: string;
            narrative?: string;
            coverage?: number;
            drift?: number;
            confidence?: number;
            ts?: number;
        };
        SearchHit: {
            node_id: string;
            type: string;
            score: number;
            snippet: string;
        };
        Violation: {
            rule: string;
            name: string;
            message: string;
        };
        /** @description approved 或 blocked 的超集；blocked 走规则闸门字段（pass/violations/checked） */
        Decision: {
            /** @enum {string} */
            status: "approved" | "blocked";
            /** @enum {string} */
            stage?: "rules" | "llm";
            decision_id?: string;
            knowledge_refs?: string[];
            context_tokens?: number;
            action?: string;
            content_type?: string;
            topic?: string | null;
            persona_fidelity_score?: number;
            generated_content?: string;
            rationale?: string;
            pass?: boolean;
            violations?: components["schemas"]["Violation"][];
            checked?: string[];
            /** @description llm=ok 或 fallback: <原因>；HTTP 端点当前不传 llm，此键为将来接入预留 */
            llm?: string;
        };
        ExecutionSpec: {
            action_id: string;
            job_id: string;
            account_id: string;
            action: string;
            topic_id?: string | null;
            decision_id?: string | null;
            knowledge_refs?: string[];
            title: string;
            content: string;
            text_b64: string;
            content_b64: string;
            content_type: string;
            task_params: {
                [key: string]: unknown;
            };
        };
        PlanResult: {
            /** @enum {string} */
            status: "approved" | "blocked";
            decision: components["schemas"]["Decision"];
            spec?: components["schemas"]["ExecutionSpec"] | null;
            /** @description approved 时必有（body 缺省 device_env 时服务端填占位值，即 dry-run 形态）；blocked 时无 */
            command?: string[];
        };
        WriteStats: {
            events: number;
            accepted: number;
            duplicates: number;
        };
        PromiseScan: {
            promises_found: number;
            notes?: string[];
        };
        CreateAccountInput: {
            platform: string;
            handle: string;
            name?: string;
            persona_id?: string;
            /** @description 人设属性（persona_props） */
            persona?: {
                [key: string]: unknown;
            };
            interests?: string[];
            device?: string;
        };
        CreateAccountResult: {
            account_id: string;
            persona_id: string;
            created: boolean;
            events: number;
        };
        ImportResultItem: components["schemas"]["CreateAccountResult"] | {
            error: string;
            handle: string | null;
        };
        ImportResult: {
            imported: number;
            total: number;
            results: components["schemas"]["ImportResultItem"][];
        };
        DecisionItem: {
            action_id: string;
            action: string;
            ts?: number;
            digest?: string;
            outcome?: string | null;
            topic_id?: string | null;
            /** @description 种子/旧数据可能无决策 ID */
            decision_id?: string | null;
            refs?: {
                id: string;
                type: string;
                label: string;
            }[];
        };
        AccountOverview: {
            persona: components["schemas"]["PersonaCard"];
            state: components["schemas"]["AccountState"];
            promises: components["schemas"]["OpenPromise"][];
            memories: components["schemas"]["RecalledMemory"][];
            episodes: components["schemas"]["Episode"][];
            digest: string;
        };
        MemoryDigest: {
            account: string;
            digest: string;
        };
        SearchResult: {
            hits: components["schemas"]["SearchHit"][];
        };
        PersonaItem: {
            persona_id: string;
            props: {
                [key: string]: unknown;
            };
            accounts: string[];
        };
        PersonaList: {
            personas: components["schemas"]["PersonaItem"][];
        };
        TopicItem: {
            topic_id: string;
            label?: string | null;
        };
        TopicList: {
            topics: components["schemas"]["TopicItem"][];
        };
        /** @description rule_id + Rule 节点全部属性 */
        RuleItem: {
            rule_id: string;
            name?: string;
            kind?: string;
            status?: string;
            text?: string;
            hard?: boolean;
            platform?: string | null;
            confirmations?: string[];
            effective_at?: number;
            jitter_window?: number;
        };
        RuleList: {
            rules: components["schemas"]["RuleItem"][];
        };
        DecisionList: {
            decisions: components["schemas"]["DecisionItem"][];
        };
        AccountList: {
            accounts: components["schemas"]["AccountListItem"][];
        };
        DecideInput: {
            account_id: string;
            /** @enum {string} */
            action_type: "post" | "comment" | "follow" | "like" | "browse";
            topic_id?: string;
            budget_tokens?: number;
        };
        PlanInput: {
            account_id: string;
            /** @enum {string} */
            action_type: "post" | "comment" | "follow" | "like" | "browse";
            topic_id?: string;
            job_id?: string;
            task_params?: {
                [key: string]: unknown;
            };
            /** @description 缺省时填占位值（dry-run 形态） */
            device_env?: {
                [key: string]: unknown;
            };
        };
        /** @description 包裹形态 {"result": {...}}（推荐）或平铺形态（result 字段直接作 body，serve 兼容） */
        ReportInput: {
            result: {
                action_id: string;
                account_id: string;
                action: string;
                topic_id?: string;
                new_post_id?: string;
                digest?: string;
                outcome?: string;
                ts?: number;
                stats?: {
                    [key: string]: unknown;
                };
                raw_text?: string;
                decision_id?: string;
                knowledge_refs?: string[];
            };
        } | {
            action_id: string;
            account_id: string;
            action: string;
            topic_id?: string;
            new_post_id?: string;
            digest?: string;
            outcome?: string;
            ts?: number;
            stats?: {
                [key: string]: unknown;
            };
            raw_text?: string;
            decision_id?: string;
            knowledge_refs?: string[];
        };
        ReportResult: {
            write: components["schemas"]["WriteStats"];
            promises: components["schemas"]["PromiseScan"];
        };
        /** @description 按 level 不同键集不同（daily={accounts,rolled}；weekly/monthly/yearly 含 expired 等）。results/rollups/consolidations 明细被剥离。 */
        MaintenanceSummary: {
            /** @description 处理的账号数 */
            accounts: number;
            /** @description daily：有归档动作的账号数 */
            rolled?: number;
            /** @description weekly：时效淘汰的记忆条数 */
            expired?: number;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
